Create trivy.yml
platform9/luigi pull request #48
Opened 2023-02-14 19:03 UTC by cruizen

GitHub action to automate scanning of vulnerabilities with Trivy

2023-02-14 19:31 UTC, cruizen commented
The output from the first run https://github.com/platform9/luigi/pull/48/checks?check_run_id=11339400064 shows that there are 2 high vulns that need to be fixed.

2023-02-15 07:05 UTC, Rohitrajak1807 requested changes

2023-02-15 07:05 UTC, Rohitrajak1807 commented on .github/workflows/trivy.yml
> +name: build
Changing this name would be better.

2023-02-15 07:05 UTC, Rohitrajak1807 commented on .github/workflows/trivy.yml
> +  build:
```suggestion
  build_image:
```

2023-02-15 07:05 UTC, Rohitrajak1807 commented on .github/workflows/trivy.yml
> +    runs-on: "ubuntu-18.04"
```suggestion
    runs-on: "ubuntu-latest"
```

2023-10-06 04:15 UTC, cruizen commented on .github/workflows/trivy.yml
> +name: build
Thanks, done

2023-10-06 15:12 UTC, Rohitrajak1807 approved these changes

2023-10-09 14:29 UTC, mithilarun approved these changes

2023-11-08 22:07 UTC, merged